apiVersion: apps/v1 
kind: Deployment
metadata:
  name: db-service
  labels:
    app: reporty
spec:
  selector:
    matchLabels:
      app: reporty
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: reporty
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: korobokvk/reporty-db-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3010